FROM rust:1.89-slim-trixie AS builder

WORKDIR /usr/src/app

RUN apt-get update && apt-get install -y \
    protobuf-compiler \
    libssl-dev \
    pkg-config \
    build-essential \
 && rm -rf /var/lib/apt/lists/*

RUN cargo install cargo-watch && \
    cargo install sqlx-cli

COPY ./Cargo.toml ./Cargo.lock ./
RUN mkdir src && echo "fn main() {}" > src/main.rs
RUN cargo build --release
RUN rm -rf src

CMD ["cargo", "watch", "-qc", "-w", "src", "-w", "Cargo.toml", "-x", "run"]
